### ISSUE TITLE
Render issues on PDF

### ISSUE THREAD

**Issue by wikiti** [litmon/gitbook-plugin-codeblock-filename#6]
Hi!

First of all, thank you for making this plugin. It has saved me a lot of time!

The rendering works perfectly when using _Web_ target. However, if the build target is PDF, the render looks something like this:

![image](https://user-images.githubusercontent.com/2975360/34966125-5c7a0670-fa51-11e7-84ff-139985d1c021.png)

The first problem that I've found is that the style is not being included. If I create a new css file, and attach it to the PDF target:

````css
/* styles/pdf.css */
.code-filename{
	background-color: rgba(0,0,0,0.07);
	display: inline-block;
	padding: 2px 8px;
	font-size: small;
	line-height: inherit;
	margin-bottom: 0px !important;
}
````

The style is rendered properly, but I get a gap between the filename and the codeblock:

![image](https://user-images.githubusercontent.com/2975360/34966166-af0dbe2c-fa51-11e7-9ba0-66f8eec4baf0.png)

I've tried to force the margin on `code` tags with no luck:

````css
/* styles/pdf.css */

pre code, code, pre /* ... */ {
  margin: 0 0;
}
````

Is there any workaround or fix this issue?
